import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "../components/Navbar"; // Import Navbar
import BootstrapClient from "../components/BootstrapClient"; // Import BootstrapClient
import Footer from "../components/Footer"; // Import Footer

const lato = Lato({
  weight: ["400", "700"], // Include 600 for semi-bold
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={`${lato.variable} antialiased`}>
        <Navbar /> {/* Add Navbar component */}
        {children}
        <BootstrapClient /> {/* Add BootstrapClient component */}
        <Footer /> {/* Add Footer component */}
      </body>
    </html>
  );
}
